name: Prettier
on: [push]

jobs:
  Prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Install NPM dependencies
        run: npm install
      - name: Prettify code
        uses: creyD/prettier_action@v4.2
        with:
          prettier_options: --write **/*.{php,js} --config .prettierrc --ignore-path .prettierignore
          prettier_plugins: '@prettier/plugin-php prettier-plugin-tailwindcss'